version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db/functions/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
