version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/tables/:/docker-entrypoint-initdb.d/tables/
      - ./db/functions/:/docker-entrypoint-initdb.d/functions/